
# Candace Savonen Oct 2023

name: Retrieve Google Drive Copy

on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * *"
  - cron: "0 12 * * *"

jobs:

  get-drive-copy:
    name: Run quiz retrieval
    runs-on: ubuntu-latest
    container:
      image: rocker/tidyverse

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}

      - name: Login as jhudsl-robot
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
          git config --global user.email "itcrtrainingnetwork@gmail.com"
          git config --global user.name "jhudsl-robot"

      - name: Run copier
        run: |
          # Make new screenshots
          chapt_urls=$(Rscript --vanilla scripts/save_copy.R \
            --key ${{ secrets.GOOGLE_PASSWORD  }} 
